config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/all_users', to: 'users#get_all_users'
      get '/claims_for_mobile', to: 'claims#index_for_mobile'
      get '/system_users', to: 'users#system_users'
      get '/category_client_email', to: 'categories#category_client_email'
      get '/forgot-password', to: 'users#forgot_password'
      get '/claims-by-categories', to: 'claims#claims_group_by_category_id'
      get '/claims-in-progress', to: 'claims#claims_group_by_tags_in_progress'
      get '/claims-fixed', to: 'claims#claims_group_by_tags_fixed'
      resources :claims
      resources :categories
      resources :user_managements
      resources :users
      resources :clients
    end
  end
  root "arrivals#index"
end

app/models/arrival.rb
class Arrival < ApplicationRecord
end

app/controllers/arrivals_controller.rb
class ArrivalsController < ApplicationController
  before_action :set_arrival, only: %i[ show edit update destroy ]

  # GET /arrivals or /arrivals.json
  def index
    @arrivals = Arrival.all
  end

  # GET /arrivals/1 or /arrivals/1.json
  def show
  end

  # GET /arrivals/new
  def new
    @arrival = Arrival.new
  end

  # GET /arrivals/1/edit
  def edit
  end

  # POST /arrivals or /arrivals.json
  def create
    @arrival = Arrival.new(arrival_params)

    respond_to do |format|
      if @arrival.save
        format.html { redirect_to arrival_url(@arrival), notice: "Arrival was successfully created." }
        format.json { render :show, status: :created, location: @arrival }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @arrival.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arrivals/1 or /arrivals/1.json
  def update
    respond_to do |format|
      if @arrival.update(arrival_params)
        format.html { redirect_to arrival_url(@arrival), notice: "Arrival was successfully updated." }
        format.json { render :show, status: :ok, location: @arrival }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @arrival.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arrivals/1 or /arrivals/1.json
  def destroy
    @arrival.destroy

    respond_to do |format|
      format.html { redirect_to arrivals_url, notice: "Arrival was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arrival
      @arrival = Arrival.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def arrival_params
      params.require(:arrival).permit(:name)
    end
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
end

app/views/arrivals/_arrival.html.erb
<div id="<%= dom_id arrival %>">
  <p>
    <strong>Name:</strong>
    <%= arrival.name %>
  </p>

</div>

app/views/arrivals/_form.html.erb
<%= form_with(model: arrival) do |form| %>
  <% if arrival.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(arrival.errors.count, "error") %> prohibited this arrival from being saved:</h2>

      <ul>
        <% arrival.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/arrivals/edit.html.erb
<h1>Editing arrival</h1>

<%= render "form", arrival: @arrival %>

<br>

<div>
  <%= link_to "Show this arrival", @arrival %> |
  <%= link_to "Back to arrivals", arrivals_path %>
</div>

app/views/arrivals/index.html.erb
<div id="arrivals">
 <h1>Welcome</h1>
</div>

app/views/arrivals/new.html.erb
<h1>New arrival</h1>

<%= render "form", arrival: @arrival %>

<br>

<div>
  <%= link_to "Back to arrivals", arrivals_path %>
</div>

app/views/arrivals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @arrival %>

<div>
  <%= link_to "Edit this arrival", edit_arrival_path(@arrival) %> |
  <%= link_to "Back to arrivals", arrivals_path %>

  <%= button_to "Destroy this arrival", @arrival, method: :delete %>
</div>